baseurl = "/"
languageCode = "en-us"
title = "The Space of Life"
theme = "hugo-ivy"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"

[permalinks]
    Chinese = "/cn/:year/:slug/"
    English = "/en/:year/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
    
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
    
[[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 3
    
[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 4

[params]
    description = "In The Space of Life, I fly my heart high."
    footer = "&copy; Mingchu Xu 许明储 2006 ～ 2019 | [GitHub](https://github.com/xmc811) | [Twitter](https://twitter.com/xmc811)"
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml", "tex"]
    highlightjsTheme = "github"
